// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCllgMJHJljW78Ev_bayxjyhuXPYExM0F8',
    appId: '1:34615812246:web:4b185d2c47510120a862b7',
    messagingSenderId: '34615812246',
    projectId: 'ethio-betting-tips',
    authDomain: 'ethio-betting-tips.firebaseapp.com',
    storageBucket: 'ethio-betting-tips.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3HzghPyTHCnd-YBHkaOYILR8AN5XhecQ',
    appId: '1:34615812246:android:82b3ab5532c7a596a862b7',
    messagingSenderId: '34615812246',
    projectId: 'ethio-betting-tips',
    storageBucket: 'ethio-betting-tips.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxjtwoYC5WJcDcfy3r5Ei3D6yuuFmudOA',
    appId: '1:34615812246:ios:8da7df7550fd3704a862b7',
    messagingSenderId: '34615812246',
    projectId: 'ethio-betting-tips',
    storageBucket: 'ethio-betting-tips.appspot.com',
    iosClientId: '34615812246-9qvmkjaefuavuhggrs2a4tr2l0n8nsli.apps.googleusercontent.com',
    iosBundleId: 'com.adwa.betting',
  );
}
